# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 3ccaaaef3337b26e3e76f87f5471c305f9de751a5e319f49db6df0c21160d81c77b18ec3d818b134a5250614877d6f11c1c3c3daef5b01859e8bda75d0e57bc6

test:
  domain_name: example.com 
  secret_key_base: d1faa84c90975e73f605f953eb4d521eb363c19cfdf9a989675d7ee14b6297815c36037e49d579a477a6718b3ed457c3f4000d4a9f9fa67d1c383e440b7102c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
